### ISSUE TITLE
New Site Request (NSR)

### ISSUE THREAD

**Issue by mzagaja** [krusynth/public-interest-tech-webring#1]
My site name: Zagaja.com

My site url: https://www.zagaja.com/

My name and email address: Matt Zagaja (mattz@codeforboston.org)

A little bit about my site: I write on an eclectic mix of topics but often and primarily on the technologies used while developing software for government. I also will sometimes share perspectives and insights from leading [Code for Boston](https://www.codeforboston.org/).

I use Jekyll and GitHub Pages.

**Comment by krusynth** [comment]
Welcome to the club @mzagaja !  Thanks for the idea!
