### ISSUE TITLE
Firesphere.dev

### ISSUE THREAD

**Issue by Firesphere** [krusynth/public-interest-tech-webring#10]
My site name: Firesphere.dev

My site url: https://firesphere.dev

My name and email address: Simon, simon@firesphere.dev

A little bit about my site: My tech ramblings, experiences, tech-mentoring, etc.

**Comment by Firesphere** [comment]
RSS Feed: firesphere.dev/articles/rss

**Comment by krusynth** [comment]
Hi there - thanks for your interest, but it doesn't look like any of your content is related to civic tech or public interest tech. That is, technology used to improve the public's access to government services or related public-good work.  Have a look at the content the rest of us are putting out for an idea of the mix of topics that's expected.  Mark's is a good place to start: https://civic.io/

**Comment by Firesphere** [comment]
I may have misunderstood the topic then! My apologies!

Loving the idea though!
