### ISSUE TITLE
Codercat Studio

### ISSUE THREAD

**Issue by Kif11** [krusynth/public-interest-tech-webring#11]
My site name:
Codercat Studio

My site url:
https://codercat.tk

My name and email address: 
Kirill kovalewskiy@gmail.com

A little bit about my site:
We are little studio of 2 people working together on WebGL, Game and life performance with tech projects.

**Comment by krusynth** [comment]
Hi there - thanks for your interest, but it doesn't look like any of your content is related to civic tech or public interest tech. That is, technology used to improve the public's access to government services or related public-good work. Have a look at the content the rest of us are putting out for an idea of the mix of topics that's expected. Mark's is a good place to start: https://civic.io/

**Comment by Kif11** [comment]
Sorry, I misunderstood that it is civic tech related. I thought it a bit more general.
Anyway, I enjoyed your post about web rings. Going to look into it more. If you have any recommendations on how to find other web rings I will appreciate that. Thank you!
