### ISSUE TITLE
Sometimes blog about gov tech adjacent things. Have new post on NASA public access policy proposal.

### ISSUE THREAD

**Issue by JustinGOSSES** [krusynth/public-interest-tech-webring#12]
My site name:
Https://JustinGosses.com

My site url: 
Https://JustinGosses.com

My name and email address: 
Justin Gosses
Jgosses@hotmail.com

A little bit about my site:

Not always about govTech but sometimes. Other times about general coding, side projects (maps that talk), or geology.

Recent post on NASA request for comment on proposed Public Access Plan: https://justingosses.com/blog/thoughts-on-nasa-public-access-plan

And mastodon post about it https://fosstodon.org/@JustinG/110845940557832869

Previously posted about finding governmental Contractor jobs at NASA. No longer in government so easier to have opinions now.

**Comment by krusynth** [comment]
Just added you, welcome to the webring!  Please don't forget to add your webring code to your site!

**Comment by JustinGOSSES** [comment]
Thanks for reminder, added to footer today
