### ISSUE TITLE
Rename the webring to public interest tech?

### ISSUE THREAD

**Issue by krusynth** [krusynth/public-interest-tech-webring#5]
Given the collapse of birdsite and the reemergence of blogging as a past-time, I think we could have a bigger tent if we rename the webring to the public interest tech webring.  The changes would be minimal, but folks would have to change the links on their sites to match a new url.  

@mzagaja @hunterowens this impacts y'all so 👍 / 👎 ?

**Comment by mzagaja** [comment]
No objection here, especially if it means more folks might consider joining.

**Comment by krusynth** [comment]
Hey @mzagaja @hunterowens I've swapped all of this and transmogrified things a bit. You'll want to change your javascript to point to `https://pitwebring.billhunt.dev/webring.js` Thanks!
