### ISSUE TITLE
New site request

### ISSUE THREAD

**Issue by joncamfield** [krusynth/public-interest-tech-webring#7]
My site name: Joncamfield.com

My site url: https://www.joncamfield.com/blog/
feed: https://www.joncamfield.com/feed 

My name and email address: OK, you're not going to believe this, but jon camfield; jon@joncamfield.com

A little bit about my site: A bit more focused on the international, "internet freedom" flavor of PIT, with some censorship and circumvention, safety and security, non-profit/NGO tech challenges, and more.

**Comment by krusynth** [comment]
Welcome to the webring, @joncamfield! You can grab the script for your site here: https://pitwebring.billhunt.dev/join/

**Comment by joncamfield** [comment]
Already live!
