### ISSUE TITLE
Request to add civic.io to the webring

### ISSUE THREAD

**Issue by mheadd** [krusynth/public-interest-tech-webring#8]
My site name: Civic Innovations

My site url: https://civic.io/

My name and email address: Mark Headd (mheadd [at] gmail [dot] com)

A little bit about my site: I write mostly about civic tech and gov tech.

**Comment by krusynth** [comment]
Thanks @mheadd, you've been added!  Please grab your webring code for your site here: https://pitwebring.billhunt.dev/join/
